default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PG_USER") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { '' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: github_engine_development

test:
  <<: *default
  database: github_engine_test

production:
  <<: *default
  database: github_engine_production
  username: github_engine
  password: <%= ENV["GITHUB_ENGINE_DATABASE_PASSWORD"] %>
